In [1]:
import json

In [2]:
import numpy

In [3]:
import tensorflow as tf

In [5]:
import numpy as np

In [12]:
a = np.random.rand(4,4,3)

In [13]:
a_t = tf.convert_to_tensor(a)

In [14]:
a_t

<tf.Tensor: id=3, shape=(4, 4, 3), dtype=float64, numpy=
array([[[0.18460587, 0.00689686, 0.51756451],
        [0.08836564, 0.73976625, 0.19996612],
        [0.64323691, 0.20018949, 0.25555362],
        [0.31827041, 0.05725154, 0.50338089]],

       [[0.36351857, 0.95797919, 0.57172305],
        [0.3014754 , 0.53317163, 0.19251167],
        [0.62339867, 0.34503763, 0.51656846],
        [0.52579644, 0.18976593, 0.39562454]],

       [[0.43231538, 0.97699118, 0.96367485],
        [0.35659375, 0.50563202, 0.53714655],
        [0.91530649, 0.6307701 , 0.41462849],
        [0.80929238, 0.41834657, 0.24008643]],

       [[0.11588485, 0.32059413, 0.05404232],
        [0.89919208, 0.11156348, 0.71302872],
        [0.66637907, 0.58829913, 0.35818307],
        [0.96482333, 0.61381942, 0.85802036]]])>

In [16]:
b_t = tf.transpose(a_t)

In [17]:
b_t.shape

TensorShape([3, 4, 4])

In [20]:
c_t = tf.reshape(b_t, [3, -1])

In [21]:
c_t.shape

TensorShape([3, 16])

In [22]:
c_t

<tf.Tensor: id=11, shape=(3, 16), dtype=float64, numpy=
array([[0.18460587, 0.36351857, 0.43231538, 0.11588485, 0.08836564,
        0.3014754 , 0.35659375, 0.89919208, 0.64323691, 0.62339867,
        0.91530649, 0.66637907, 0.31827041, 0.52579644, 0.80929238,
        0.96482333],
       [0.00689686, 0.95797919, 0.97699118, 0.32059413, 0.73976625,
        0.53317163, 0.50563202, 0.11156348, 0.20018949, 0.34503763,
        0.6307701 , 0.58829913, 0.05725154, 0.18976593, 0.41834657,
        0.61381942],
       [0.51756451, 0.57172305, 0.96367485, 0.05404232, 0.19996612,
        0.19251167, 0.53714655, 0.71302872, 0.25555362, 0.51656846,
        0.41462849, 0.35818307, 0.50338089, 0.39562454, 0.24008643,
        0.85802036]])>

In [25]:
d_t = tf.transpose(a_t, perm=[2,0,1])

In [26]:
d_t

<tf.Tensor: id=15, shape=(3, 4, 4), dtype=float64, numpy=
array([[[0.18460587, 0.08836564, 0.64323691, 0.31827041],
        [0.36351857, 0.3014754 , 0.62339867, 0.52579644],
        [0.43231538, 0.35659375, 0.91530649, 0.80929238],
        [0.11588485, 0.89919208, 0.66637907, 0.96482333]],

       [[0.00689686, 0.73976625, 0.20018949, 0.05725154],
        [0.95797919, 0.53317163, 0.34503763, 0.18976593],
        [0.97699118, 0.50563202, 0.6307701 , 0.41834657],
        [0.32059413, 0.11156348, 0.58829913, 0.61381942]],

       [[0.51756451, 0.19996612, 0.25555362, 0.50338089],
        [0.57172305, 0.19251167, 0.51656846, 0.39562454],
        [0.96367485, 0.53714655, 0.41462849, 0.24008643],
        [0.05404232, 0.71302872, 0.35818307, 0.85802036]]])>

In [27]:
e_t = tf.transpose(a_t, perm=[2,1,0])

In [28]:
e_t

<tf.Tensor: id=17, shape=(3, 4, 4), dtype=float64, numpy=
array([[[0.18460587, 0.36351857, 0.43231538, 0.11588485],
        [0.08836564, 0.3014754 , 0.35659375, 0.89919208],
        [0.64323691, 0.62339867, 0.91530649, 0.66637907],
        [0.31827041, 0.52579644, 0.80929238, 0.96482333]],

       [[0.00689686, 0.95797919, 0.97699118, 0.32059413],
        [0.73976625, 0.53317163, 0.50563202, 0.11156348],
        [0.20018949, 0.34503763, 0.6307701 , 0.58829913],
        [0.05725154, 0.18976593, 0.41834657, 0.61381942]],

       [[0.51756451, 0.57172305, 0.96367485, 0.05404232],
        [0.19996612, 0.19251167, 0.53714655, 0.71302872],
        [0.25555362, 0.51656846, 0.41462849, 0.35818307],
        [0.50338089, 0.39562454, 0.24008643, 0.85802036]]])>

In [29]:
b_t

<tf.Tensor: id=7, shape=(3, 4, 4), dtype=float64, numpy=
array([[[0.18460587, 0.36351857, 0.43231538, 0.11588485],
        [0.08836564, 0.3014754 , 0.35659375, 0.89919208],
        [0.64323691, 0.62339867, 0.91530649, 0.66637907],
        [0.31827041, 0.52579644, 0.80929238, 0.96482333]],

       [[0.00689686, 0.95797919, 0.97699118, 0.32059413],
        [0.73976625, 0.53317163, 0.50563202, 0.11156348],
        [0.20018949, 0.34503763, 0.6307701 , 0.58829913],
        [0.05725154, 0.18976593, 0.41834657, 0.61381942]],

       [[0.51756451, 0.57172305, 0.96367485, 0.05404232],
        [0.19996612, 0.19251167, 0.53714655, 0.71302872],
        [0.25555362, 0.51656846, 0.41462849, 0.35818307],
        [0.50338089, 0.39562454, 0.24008643, 0.85802036]]])>